config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  post 'posts/copy_sessions' => 'posts#copy_sessions', as: :copy_sessions

  get 'posts/graphics' => 'posts#graphics', as: :graphics

  post 'posts/graphics' => 'posts#graphics_sessions', as: :graphics_sessions

  get 'posts/preview' => 'posts#preview', as: :preview

  resources :emoticons

  resources :languages

  resources :users

  resources :posts do
    member do
      put "like", to: "posts#upvote"
    end
  end

  root 'posts#index'

end

app/models/emoticon.rb
class Emoticon < ActiveRecord::Base
  has_many :posts
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :post
end

app/models/language.rb
class Language < ActiveRecord::Base
  has_many :posts
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!



end

app/controllers/emoticons_controller.rb
class EmoticonsController < ApplicationController
  has_many :posts
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
   #needs to be accessible to posts & USERS?????????
   def create
    @language = Language.new
    @language.save #need to check this method but this is where we need to redirect to next page
      redirect_to @input
    end

  def index
    @language = Language.all.order('created_at DESC') #incase we want to show them in an index
  end

 
  
  def show
    @language = Language.find(:id) 
  end

  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
#Need to give access to images, languages, input
  before_action :find_post, only: [:show, :edit, :update, :destroy, :upvote]
  skip_before_action :authenticate_user!, only: [:new, :copy_sessions, :graphics, :graphics_sessions]

  def index
    @posts = Post.all
    # Need to only render text if given, not "/posts/xx"
    render "posts/feed"
  end

  def show
    render 'posts/show'
  end

  def new
    @post = Post.new
    render 'posts/input'
  end

  def create
    @post = current_user.posts.build#(post_params)
    @post.top_copy = session[:top_copy]
    @post.bottom_copy = session[:bottom_copy]
    @post.emoticon_id = session[:emoticon_id]
    @post.language_id = session[:language_id]
    @post.image_url = session[:image_url]
    if @post.save
     redirect_to @post
    else
      render 'posts/input'
    end
  end

  def edit
    render 'posts/input'
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: "Edited"
    else
      render 'posts/emotions'
    end
  end

  def upvote
    @post.upvote_by current_user
    redirect_to :back
  end

  def copy_sessions
    session[:top_copy] = params["post"]["top_copy"]
    session[:bottom_copy] = params["post"]["bottom_copy"]
    redirect_to graphics_path
  end

  def graphics
    @post = Post.new
    render 'posts/emotions'
  end

  def graphics_sessions
    session[:emoticon_id] = params["post"]["emoticon_id"]
    session[:language_id] = params["post"]["language_id"]
    redirect_to preview_path
  end

  def preview
    @url = "http://apimeme.com/meme?meme=#{Post.random_option}&top=#{session[:top_copy]}&bottom=#{session[:bottom_copy]}"
    session[:image_url] = @url
  end



  private

  def post_params
    params.require(:post).permit(:top_copy, :bottom_copy, :user_id, :language_id)
  end

  def find_post
    @post = Post.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/emoticons_helper.rb
module EmoticonsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/emotions.html.erb
<h1>Copy</h1>

<%= form_for(@post, url: graphics_sessions_path) do |f| %>

  <p>
    <%= f.label :emoticon_id %>
    <%= f.text_field :emoticon_id %>    
  </p>

  <p>
    <%= f.label :language_id %>
    <%= f.text_field :language_id %>    
  </p>



  <%= f.submit %>
<% end %>

app/views/posts/feed.html.erb
<h1>Feed</h1>

<ol>
<% @posts.each do |post| %>
  <li><%= link_to post.top_copy, post_path(post) %></li>
<% end %>
</ol>

<p><%= link_to "New Post", new_post_path %></p>

app/views/posts/index.html.erb
<h1>Index</h1>

app/views/posts/input.html.erb
<h1>Input</h1>

<%= form_for(@post, url: copy_sessions_path) do |f| %>

  <p>
    <%= f.label :top_copy %>
    <%= f.text_field :top_copy %>    
  </p>

  <p>
    <%= f.label :bottom_copy %>
    <%= f.text_field :bottom_copy %>    
  </p>


  <%= f.submit %>
<% end %>

app/views/posts/preview.html.erb
<h1>Preview</h1>

<%= image_tag(@url) %>
<br/>
<%= link_to "Generate New Image", preview_path %>
<br/>

<%= session[:emoticon_id] %>
<br/>
<%= session[:language_id] %>
<br/>

<%= link_to "Create Post", posts_path, method: :post %>

app/views/posts/show.html.erb
<h1>Show That Shit</h1>

<%= image_tag(@post.image_url) %>
<br/>
<%= @post.emoticon_id %>
<br/>
<%= @post.language_id %>
<br/>
<%= @post.user.created_at %>

<div class="col-md-6">
  <div class="btn-group pull-right">
    <%= link_to like_post_path(@post), method: :put, class: "btn btn-default" do %>
      <span class="glyphicon glyphicon-heart">
        <%= @post.get_upvotes.size %>
      </span>
    <% end %>
  </div>
</div>